platform :ios, '10.0'
use_frameworks!

target 'Example' do
    
    pod 'ProHUD',   :path => '..'
    
    pod 'SnapKit', '4.2.0'
    pod 'Inspire', '1.0.5' # :path => '../Inspire'
    
end



#pod install --verbose --no-repo-update      #安装命令
#pod update --verbose --no-repo-update       #更新命令
